### ISSUE TITLE
better way to calculate distance

### ISSUE THREAD

**Issue by Fosowl** [Huntears/MUL_my_defender#1]
function float cg_get_distance(sfVector2f v1, sfVector2f v2) in /lib/cg/cg_get_distance.c could be improved by using math ;)

refer to https://fr.wikipedia.org/wiki/Distance_entre_deux_points_sur_le_plan_cart%C3%A9sien

or https://github.com/Fosowl/S.T.A.R.S.E.T-Game-Engine/blob/76cca3832c7772db183e8055bc7db9b3a3534488/engine/src/physics/math_misc.c

**Comment by Huntears** [comment]
dude, come on
